-- phpMyAdmin SQL Dump
-- version 4.0.10.14
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Dec 09, 2016 at 02:09 PM
-- Server version: 10.0.27-MariaDB-cll-lve
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `crosstec_7Tennis`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblQuestion`
--

CREATE TABLE IF NOT EXISTS `tblQuestion` (
  `id` int(11) NOT NULL,
  `categoryid` int(11) NOT NULL,
  `title` varchar(1000) NOT NULL,
  `description` longtext,
  `priority` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tblQuestion`
--

INSERT INTO `tblQuestion` (`id`, `categoryid`, `title`, `description`, `priority`) VALUES
(1, 1, 'What is the 7TENNIS app?', '<div><span>7TENNIS gives viewers\nmore tennis than ever before. Via the app or website viewers can follow the entire\nSummer of 7TENNIS, including the Australian Open and pre-tournaments: the\nHopman Cup, Brisbane International, APIA International Sydney and the Kooyong\nClassic. 7TENNIS will also stream content from the Davis Cup, Fed Cup and\nWimbledon. It''s the must-have app for tennis fans.</span><br></div>', 1),
(2, 1, 'How can I get 7TENNIS?', '<p>\r\n\r\nYou can download 7TENNIS Android or iOS app\r\nfor free* from Google Play and Apple Store. TVOS is also available.\r\n\r\n&nbsp;<span>\r\n</span></p><p><span>\r\n<span>The product is also available on the web at <a href="https://7tennis.com.au" target="_blank" rel="nofollow">7tennis.com.au</a> and through smart TVs with\r\nTelstraTV, FetchTV and AppleTV. </span></span></p><p><span><span>*Data Charges apply</span></span></p>', 3),
(3, 2, 'How can I upgrade to a Premium account?', 'There are two ways to upgrade to Premium:&nbsp;<div><b><br></b></div><div><b>In-app</b>: you can upgrade easily in the app by -&nbsp;<br></div><div><span><span>1.&nbsp;</span>Signing in to iTunes Store</span></div><div><span><span>2.&nbsp;</span>Touch ID</span></div><div><span><span>3.&nbsp;</span>Android password - p</span>assword confirmation enables you to use\nyour Google Play account to purchase the 7TENNIS app. You can also add a new\ncredit/debit card or Paypal in-app to upgrade.&nbsp;</div><div>-You will always be asked to confirm your\nin-app purchase.&nbsp;<br></div><div><br></div><div><b>By web</b>: you upgrade using either -&nbsp;</div><div>1.&nbsp;Paypal</div><div>2.&nbsp;MasterCard or Visa card payment&nbsp;</div><div><br></div><div>*Please note data charges apply.&nbsp;</div><div>*Unfortunately we do not support Premium access\non Fetch, Apple and Telstra TV box sets.<br></div>', 3),
(4, 2, 'What can I access with a premium upgrade?', '<span><span>7TENNIS Premium gives\r\nyou selected full match replays and all 620 matches streamed in brilliant HD.&nbsp;As a\r\nPremium user you will not be served pre-roll ads so you can&nbsp;get to the action faster.</span><br></span>', 2),
(5, 3, 'What do I do if I forget my 7TENNIS password?', 'If you forget your password in the sign-in\nprocess, simply click on the "forgot?" or "forgot your password?" text\nimmediately below the sign-in box and follow the prompts to reset your\npassword.<i>&nbsp;</i><span>\n\n\n\n<span>You can also use the "Forgot Password" link\navailable at <a href="http://7Tennis.com.au/forgot " target="_blank" rel="nofollow" title="Link: http://www.7tennis.com.au/forgot">7Tennis.com.au/forgot</a><a href="http://7Tennis.com.au/forgot " target="_blank" rel="nofollow" title="Link: http://7Tennis.com.au/forgot ">&nbsp;</a></span></span><span><br></span>', 1),
(6, 3, 'Is the streaming on 7TENNIS apps unmetered?', '<span><span>No, the streaming is\r\nmetered and you will incur data charges as per your mobile/home internet plan.\r\n7TENNIS apps use adaptive bitrate streaming that automatically adjusts the\r\nquality of the video based on the quality of your internet connection.</span><br></span>', 2),
(7, 4, 'Why is my video constantly buffering (starting/stopping)?', 'The app uses adaptive\r\nstreaming technology to automatically adjust the quality of your streaming to\r\nsuit your internet speed and the capability of your device.\r\n\r\n<span>For an optimal streaming experience we recommend a minimum internet data\r\nspeed of at least 3Mbps or above. To check your internet speed, please\r\nvisit&nbsp;<a href="http://speedtest.net" target="_blank" rel="nofollow" title="Link: http://speedtest.net">speedtest.net</a>. This site allows you\r\nto see your download and upload speeds; the higher the number, the better the\r\nspeed. If the issues are consistent, it may be worth contacting your internet\r\nservice provider.</span>\r\n\r\nThis issue can occur for several reasons. These reasons include:\r\n\r\n<ul>\r\n <li>Low bandwidth\r\n     connection</li>\r\n <li>Other users on\r\n     your network sharing the internet connection</li>\r\n <li>Poor internet\r\n     connection at the time of viewing the video. On occasions internet\r\n     connections can drop out or are overloaded due to high internet traffic.\r\n     Speak with your ISP if you notice any ongoing issues.</li>\r\n <li>Wireless internet\r\n     connections can get interrupted resulting in playback issues (speak with\r\n     your ISP if you notice any ongoing issues).</li>\r\n</ul>\r\n\r\nIf you continue to experience technical issues, please contact our\r\nfriendly Customer Support centre via email, they will be happy to answer\r\nqueries and help you resolve any issues at&nbsp;<a href="http://7tennis.com.au/support/contact" target="_blank" rel="nofollow">http://7tennis.com.au/support/contact</a>.&nbsp;', 2),
(8, 4, 'The video/audio quality on the 7TENNIS app is not optimal, what can I do about this?', 'The app uses adaptive\nstreaming technology to automatically adjust the quality of your streaming to\nsuit your internet speed.\n\n<span>For an optimal\nstreaming experience we recommend a minimum\ninternet data speed of at least 3Mbps or above.</span>&nbsp;<div><br><div>To check the speed of\nyour internet, please visit&nbsp;<a href="http://speedtest.net" target="_blank" rel="nofollow">speedtest.net</a>. This site allows you to see your download and upload speeds; the\nhigher the number, the better the speed. If the issues are consistent, it may\nbe worth contacting your internet service provider.\n\nBelow are the Internet\ndownload speed recommendations per stream:&nbsp;<br></div><div>&nbsp;</div><div>0.8 Megabits per second - Minimum required broadband connection speed</div><div>\n\n3.0 Megabits per second\n- Recommended for SD quality&nbsp;</div><div><br></div><div>If you continue to experience technical issues, please contact our\nfriendly Customer Support centre via email, they will be happy to answer\nqueries and help you resolve any issues at&nbsp;<a href="http://7tennis.com.au/support/contact" target="_blank" rel="nofollow" title="Link: http://7tennis.com.au/support/contact">7tennis.com.au/support/contact</a><span>.</span></div></div>', 1),
(15, 1, 'What content is available on the app?', '<span>\n\nYou will have access to all of Seven''s live\ncoverage of the Summer of 7TENNIS on channels 7, 7TWO and 7mate; plus\nnon-broadcast action streamed from additional courts (up to 16 additional\ncourts for the Australian Open), curated Video on Demand short-form highlights,&nbsp;streaming to smart TVs with Chromecast and\nAirplay (Casting varies by device see Tech FAQs).&nbsp;</span><span>&nbsp;</span><div><span><span><br></span></span></div><div><span><span>You can also access selected full\nmatch replays and watch in brilliant HD by upgrading to the Premium version\nof the app for $9.99*</span><br></span><br></div><div>*Data charges apply</div>', 2),
(23, 1, 'What do I get if I upgrade to Premium?', '<p>\r\n\r\nYou can upgrade to 7TENNIS Premium for\r\n$9.99 to access selected full match replays, get all 620 matches live&nbsp;streamed in brilliant&nbsp;HD and no pre-rolls so you can get to the action faster.&nbsp;</p><p><span>\r\n\r\n<span>Interested in getting Premium? Purchase in the app\r\nor go to <a href="http://7Tennis.com.au/premium/get" target="_blank" rel="nofollow">7Tennis.com.au/premium/get</a><span>&nbsp;&nbsp;</span></span></span></p>', 4),
(24, 4, 'Why is the stream on my device delayed when compared to my TV?', '<span>Some viewers may experience delays of up to 110 sec behind broadcast\r\nwhen viewed on smartphones, tablets and computers. This is specific to the\r\ndevice you are using and may not always happen. We are working with our\r\nprovider to improve the stream latency.</span>', 3),
(25, 1, 'Do I need to set up an account to use the 7Tennis app or website?', '\n\nNo, you do not need to set up an account to\nview the content on our website or free app, if you are in the app you can\nchoose to "skip" the sign in process.&nbsp;<div><span><br></span></div><div><span>However if you want to upgrade to a Premium account\nyou must have a 7TENNIS account.&nbsp;</span><div>You can sign-up either\nvia an email address or by entering your Facebook/Google credentials in the app\nor website at: <a href="http://7Tennis.com.au/premium/get" target="_blank" rel="nofollow">7Tennis.com.au/premium/get</a><br></div></div>', 5),
(26, 1, 'How can I get an account?', '\n\nYou can sign-up either\nvia an email address or by entering your Facebook/Google credentials in the app\nor website.\n\nAt the end of the sign-up process you will\nbe asked if you would like to upgrade to premium.&nbsp;<div><br></div><div>\n<b>In the app:</b> by continuing with Facebook, Google or\nemail you will be able to set up a 7TENNIS account.&nbsp;</div><div></div><img alt="" src="http://7support-static.swmstaging.com.au/Mob-new-account-2.jpg" title="Image: http://7support-static.swmstaging.com.au/Mob-new-account-2.jpg"><div><br></div><div><div><b>On the website:</b>&nbsp;click on either the Get Premium or Sign in Button.</div></div><img alt="" src="http://7support-static.swmstaging.com.au/web-new-account-1.jpg" title="Image: http://7support-static.swmstaging.com.au/web-new-account-1.jpg"><div><br><div><div>Select the New Account tab and follow the prompts to complete the process.</div></div><img src="http://7support-static.swmstaging.com.au/web-step-2-new-account.jpg" onclick="lightbox(" http:="" cross-technology.com="" 7tennis="" uploads="" web="" step="" 2="" new="" account.jpg");"="" title="Image: http://7support-static.swmstaging.com.au/web-step-2-new-account.jpg"></div>', 6),
(27, 1, 'How long will I have access to 7TENNIS?', '<span>7TENNIS app will launch for the Summer of 7TENNIS and Premium features will be available from 1st January until 7th February 2017*.</span>\r\n\r\n&nbsp;<div><span><br></span></div><div>\r\n\r\n<span>*SevenWestMedia reserves the right to extend\r\nthis availability period to a later date.</span></div>', 7),
(28, 2, 'If I have been granted a Premium Code, how can I get access to my premium account?', '<span>If you have a Premium\ncode, please go to our website at: <a href="http://7tennis.com.au/premium/get" target="_blank" rel="nofollow">7tennis.com.au/premium/get</a>,\nselect "I have a premium code" and register your details. Once registered,\nplease follow the prompts to enter the unique code to gain access to your\n7TENNIS Premium account.</span>', 4),
(29, 2, 'Is my Premium account transferable?', '<span>No, unfortunately you\r\ncannot transfer your Premium account to a different user. If you are having\r\ntrouble accessing your account please get in touch with our friendly customer support\r\nteam at: <a href="http://7tennis.com.au/premium/get" target="_blank" rel="nofollow" title="Link: http://7tennis.com.au/premium/get">7tennis.com.au/support/contact</a></span>', 5),
(30, 2, 'I had access to a Premium account, but I am unable to use premium features anymore. What can I do?', '<span>Please get in touch\r\nwith our friendly customer support team with any queries or issues you may have\r\nat: <a href="http://7tennis.com.au/support/contact" target="_blank" rel="nofollow">7tennis.com.au/support/contact</a></span>', 6),
(31, 2, 'What is your refund policy?', 'In circumstances\r\nwhere there is a major failure with the Premium Service or where the Premium\r\nService fails to be of acceptable quality, customers may be eligible for a\r\nrefund and can request one via the online form found at our support page. You\r\nmust have purchase invoice handy and submit the reason for your request.<div>We will use best\r\nendeavours to respond within 24 hours.<br></div><div><br></div><div>Your claim will\r\nbe assessed, and if your claim is eligible, we will process a refund to your\r\ncredit card or PayPal account within 10 business days, subject to any delays\r\ncaused by your credit card provider or PayPal.</div><div><br></div><div>We do not provide refunds for change of mind\r\nor where technical issues occur that are beyond our reasonable control, such as\r\nissues with your device, unsuitability of your device or broadband plan, or\r\nnetwork congestion.</div><div><br></div><div>\r\n\r\nFor further support, please contact our friendly\r\nCustomer Support Centre here&nbsp;<a href="http://7tennis.com.au/support/contact" target="_blank" rel="nofollow">7tennis.com.au/support/contact</a>&nbsp;and make sure that you have your purchase\r\ninvoice handy if you would like to discuss a refund.</div>', 7),
(32, 2, 'Will I see ads when viewing content as a premium user?', 'Yes, there will still be broadcast and\r\ndigital advertising served within streams, but as a premium user you will see fewer\r\ninterruptions as there are no digital ads at the start of each stream and only\r\nadvertising from our broadcast partners within a stream.&nbsp;<div><br></div><div><span>*Please refer to the Terms and Conditions for\r\nfurther information.</span></div>', 8),
(33, 3, 'How are you helping me monitor my data usage when I have streams open?', 'There are two ways to help limit data usage\nin the 7TENNIS app. &nbsp; &nbsp;<div>Option 1-\n\nIn settings you can opt to turn off\ncellular streaming when Wifi is not available.</div><img alt="" src="http://7support-static.swmstaging.com.au/cellular-streaming-SD.jpg" title="Image: http://7support-static.swmstaging.com.au/cellular-streaming-SD.jpg"><div>Premium users who have access to HD streams\ncan also opt to turn off HD cellular streaming when Wifi is not available in\nthe app settings.</div><img alt="" src="http://7support-static.swmstaging.com.au/HD-cellular-streaming.jpg" title="Image: http://7support-static.swmstaging.com.au/HD-cellular-streaming.jpg"><div><br></div><div>Option 2 - \n\nWe will ask you if you are still watching\nafter your device has been left unattended for 15 minutes*. If you do not\nrespond within the 10 second countdown the video stream will be stopped\nautomatically. \n\n&nbsp;&nbsp;</div><div><span>*You can set how regularly you are given this\nprompt in the settings section of the app:</span></div><img src="http://7support-static.swmstaging.com.au/Reminder-slidebar.jpg" onclick="lightbox(" http:="" cross-technology.com="" 7tennis="" uploads="" reminder="" slidebar.jpg");"="" title="Image: http://7support-static.swmstaging.com.au/Reminder-slidebar.jpg"><div><br></div>', 3),
(34, 3, 'Is it possible to rewind live streams?', '<span>No, you are unable to rewind live streams in 7TENNIS, however you can view\r\nshort-form Video on Demand (VoD) highlights for free and watch full match replays\r\nwith a 7TENNIS Premium account.</span>', 4),
(35, 3, 'Can I download content to my mobile device?', '<span>No, this is a\r\nstreaming service so download is not available. Alternatively we will offer\r\nshort-form Video on Demand (VoD) highlights for free and full match replays\r\nwith a 7TENNIS Premium account.</span>', 5),
(36, 3, 'Can I receive notifications of upcoming matches and news?', '<span>Yes, you can choose to receive Push\r\nNotifications from Channel Seven reminding you of upcoming action and news. You\r\ncan select this feature during the sign-up process or in settings.<br></span><img src="http://7support-static.swmstaging.com.au/Push-notifications.jpg" onclick="lightbox(" http:="" cross-technology.com="" 7tennis="" uploads="" push="" notifications.jpg");"="" title="Image: http://7support-static.swmstaging.com.au/Push-notifications.jpg">', 6),
(37, 3, 'Will subtitles be available on the 7TENNIS?', '<span>Sorry, subtitles and\r\nclosed captions will not be available on the app or website.</span>', 7),
(38, 3, 'Will 7TENNIS be available in different languages?', '<span>7TENNIS will be\r\navailable in English.</span>', 8),
(39, 3, 'Why is commentary missing from some of the streams?', '<span>All matches shown on Seven''s broadcast streams will have commentary.\nUnfortunately a small number of matches broadcast through live court streams\nmanaged by Tennis Australia will have no commentary.</span>', 9),
(40, 3, 'What can I find in the highlights section?', '<span>The highlights\nsection brings you exclusive curated videos of the Tennis including the best\nmoments of the day''s action, coverage and player profiles.</span>', 10),
(41, 3, 'What are the orange coloured numbers following player names? ', '<span>These are the players'' seed numbers for the\ntournament. The player rankings are available in the player profile section of\nthe 7TENNIS app.<br></span><img src="http://7support-static.swmstaging.com.au/Seeds.jpg" onclick="lightbox(" http:="" cross-technology.com="" 7tennis="" uploads="" seeds.jpg");"="" title="Image: http://7support-static.swmstaging.com.au/Seeds.jpg">', 11),
(42, 4, 'Is it possible to rewind live streams?', '<span>No, we are sorry but\r\nyou are unable to rewind live streams in 7TENNIS.</span>', 4),
(43, 4, 'If I am on the Gold Coast, which broadcast coverage will I see?', '<span>The Gold Coast will\r\nreceive broadcast from Brisbane.</span>', 5),
(44, 4, 'Is Seven''s Tennis coverage broadcast in HD?', '<span>Seven''s broadcast channels will be transmitted as SD/HD, if you would\nlike to view live court streams in HD you can upgrade to premium access.&nbsp;</span>', 6),
(45, 5, 'What are the minimum requirements to access the 7TENNIS app?', 'You must be located in Australia and be\nover the age of 15, or otherwise have a parent''s permission to use the service.\n\n&nbsp;&nbsp;<div><br></div><div>You must be using a supported device and\nfor optimal streaming we recommend a minimum internet data speed of at least\n3Mbps or above.\n\n<span>Sign-up is voluntary for the free service but to\nenjoy a premium service you will need an account.</span></div>', 1),
(46, 5, 'Can I watch the 7TENNIS app on my TV?', 'The 7TENNIS app is not available on Smart\r\nTVs but you can watch 7TENNIS on Fetch TV, Apple TV and Telstra TV Set Top\r\nBoxes.&nbsp;<span>Alternatively you could connect your laptop to\r\nyour TV using an HDMI cable to get a big screen experience.&nbsp;</span>', 2),
(47, 5, 'Is 7TENNIS app available on PlayStation or Xbox?', '<span>Sorry, 7TENNIS is not\r\navailable on these gaming consoles. For other options please see our response\r\nto the question: What devices support the 7TENNIS app?</span>', 3),
(48, 5, 'What devices support the 7TENNIS app?', '7TENNIS app should be available on supported\niOs and android devices. Supported mobile devices:&nbsp;<div><br><div><b>Android Smart Phone</b>\n-&nbsp; Samsung Galaxy SIII , HTC One X , Asus\nGoogle Nexus 7, Samsung Galaxy S6 , Samsung Galaxy S6 Edge, Samsung Galaxy S5,\nSamsung Galaxy Note 5, Samsung Galaxy Note 3 , Samsung Galaxy Note 2, Nexus 5 ,\nLG G3&nbsp;</div><div><b>Android Tablet </b>-&nbsp; Asus Google\nNexus 7, Samsung Galaxy Note 10.1, Samsung Tab 2, Samsung Galaxy Tab 4, Nexus\n10, Samsung Galaxy Tab 3, Sony Xperia Z Tablet, Samsung Galaxy Tab S2, Asus\nGoogle Nexus 7&nbsp;<br></div><div><br></div><div><b>iOS Smart Phone</b> -\niPhone 6 Plus, iPhone 6, iPhone 5S, iPhone 5<div><b>iOS\nTablet- </b>iPad Mini 3, iPad Mini, iPad Air, iPad 4, iPad 3\n\nTV&nbsp;<br></div><div><br></div><div><b>Set Top Boxes</b> - Apple TV, Telstra TV and\nFetch TV.\n\n&nbsp;&nbsp;</div><div><br></div><div><span><b>Web </b>-&nbsp;You can also access 7TENNIS through our\nwebsite at <a href="http://www.7tennis.com.au" target="_blank" rel="nofollow">http://www.7tennis.com.au/</a> &nbsp;from a desktop or your laptop computer*. Supported browsers are&nbsp;</span><span>Microsoft Edge, Internet Explorer, Chrome,\nFirefox, Safari, Opera.</span></div></div></div><div><br></div>', 4),
(49, 5, 'On how many devices can I watch 7TENNIS?', '<span>There is no limit on\r\nthe number of devices; however you can stream a maximum of 2 devices\r\nsimultaneously on the same premium account.</span>', 5),
(50, 5, 'What are the other ways to watch Channel Seven''s coverage of the "Summer of 7TENNIS"?', '7TENNIS will give you the most complete\ncoverage of the ''Summer of 7TENNIS'' but there are other options to view our\nbroadcast channel coverage:\n\n&nbsp;&nbsp;<div><br><div><span><b>On TV -&nbsp;</b>You\nwill be able to watch our Tennis coverage LIVE and FREE on your TV by tuning\ninto 7, 7TWO or 7mate and channel 70 in HD.</span>&nbsp;</div><div><br></div><div><span>Internet\nStreaming -<span><br>\n</span><b>Option\n1</b> - Watch on 7live.com.au or the 7Live app, both contain live streams of 7,\n7TWO and 7mate.&nbsp;</span></div><div>\n\n<b>Option 2</b> - Watch on Plus7.&nbsp;Our\ncoverage on 7, 7Two and 7mate will be available on Plus7. Plus 7 is available\nas an app on Android, iOS, 4G Apple TV and Telstra TV. Alternatively you could\nwatch on the web at&nbsp;<a href="http://au.tv.yahoo.com/plus7" target="_blank" rel="nofollow">http://au.tv.yahoo.com/plus7</a> <span><br></span></div></div>', 6),
(51, 5, 'Why am I not able to watch 7TENNIS in my area?', '<span>Our Tennis coverage\r\nis for Australian viewers only. If you reside outside of Australia or have an\r\nIP address that is not Australian you will not be able to watch our coverage.</span>', 7),
(52, 6, 'What is your Privacy Policy ?', '<span>Please see our privacy policy&nbsp;here:\r\n<span><b><i>UPDATE TO PRIVACY POLICY URL</i></b></span></span>', 5),
(53, 6, 'What personal details do you collect?', 'As part of the sign in process you only need to provide your name and\r\nemail address. <span>It is optional to share your gender and date of birth details. <span>Alternatively you can also sign in using your Facebook or\r\nGoogle credentials.</span></span>', 2),
(54, 6, 'What are you collecting my personal details for and who will you disclose them to?', '<div>Please see our privacy statement here:&nbsp;<a href="http://www.seven.com.au/privacy" target="_blank" rel="nofollow">http://www.seven.com.au/privacy</a> </div><div><br></div>', 4),
(55, 6, 'What are the Terms of Use of the 7TENNIS app?', '<span>The Terms of Use can\r\nbe viewed at:&nbsp;<a href="http://www.7tennis.com.au/terms" target="_blank" rel="nofollow">http://www.7tennis.com.au/terms</a> </span><u></u>', 1),
(56, 2, 'What can I access for free*?', 'Live streams of Seven''s broadcast channels 7, 7TWO, 7mate, 7Flix and Racing.com, plus non-broadcast live streams from additional courts (3 courts in the Brisbane and Sydney tournaments and up to 16 courts for the Australian Open) in SD, curated Video On Demand highlights and streaming capability to smart TVs with Chromecast and Airplay (varies by device) all for free*.<div><br></div><div>*Data charges apply.</div>', 1),
(57, 6, 'Why do you need my email address?', '<span>We require your email address so that if you choose to upgrade to a 7TENNIS&nbsp;Premium account&nbsp;we can\nvalidate your purchase&nbsp;and send the relevant&nbsp;tax invoice.</span><div><span><br></span></div><div><span>In addition to validating a Premium upgrade we also need your email address so that we can contact you to reset your 7TENNIS password&nbsp;in the case that you forget it.</span></div>', 3);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
